CONFIG_ZMK_SLEEP=y
CONFIG_BT_CTLR_TX_PWR_PLUS_4=y
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
CONFIG_ZMK_POINTING=y
CONFIG_ADC=y
CONFIG_INPUT=y
CONFIG_ANALOG_INPUT=y
CONFIG_ANALOG_INPUT_ADC_RES=12

CONFIG_MORE_ERGO_STATUS_LED=y